commit_message: 'feat: translations for %language%'
append_commit_message: false

files:
  - source: /src/main/resources/assets/pissnshit/lang/en_us.json
    translation: /src/main/resources/assets/pissnshit/lang/%locale_with_underscore%.json
    update_option: update_as_unapproved