commit_message: 'feat: translations for %language%'
append_commit_message: false

pull_request_title: 'feat: update translations'
pull_request_labels:
  - translation

files:
  - source: /src/main/resources/assets/pissnshit/lang/en_us.json
    translation: /src/main/resources/assets/pissnshit/lang/%locale_with_underscore%.json
    update_option: update_as_unapproved